---
default_user: "ansible"

# Project
project_name: "flask-app"
project_path: "/opt/{{ project_name }}/{{ env }}"

# Deploy
deploy_branch: "{{ lookup('env', 'DEPLOY_BRANCH') }}"

# Domain records
default_hosted_zone: "kelvedler.dev"

# Docker images
docker_image_traefik: "traefik:2.10.4"
docker_image_postgres_app_server: "postgres:15.2-alpine"
docker_image_redis_app_server: "redis:7.0.11-alpine"
docker_image_elasticsearch: "elasticsearch:8.7.0"
docker_image_app_server: "kelvedler/flask-app-backend"
docker_image_rabbitmq_app_server: "rabbitmq:3.11.16-management-alpine"
docker_image_kibana: "docker.elastic.co/kibana/kibana:8.7.0"
docker_image_vector: "timberio/vector:nightly-alpine"

# Docker containers
docker_app_name: "app"

# Docker compose project name
compose_project_name: "{{ project_name }}-{{ env }}"

# Traefik
traefik_network_name: "traefik-pub-net"

# App settings
app_secret_key: "{{ lookup('env', 'FLASK_APP_APP_SECRET_KEY') }}"
app_repository: "https://github.com/Kelvedler/flask_app" 

# Websockets
websockets_host: "0.0.0.0"
websockets_port: 8001

# Database
database_name: "{{ project_name }}-{{ env }}"
database_host: "database"
database_port: 5432
database_user: "{{ lookup('env', 'FLASK_APP_DATABASE_USER') }}"
database_pass: "{{ lookup('env', 'FLASK_APP_DATABASE_PASS') }}"

# Elasticsearch
elasticsearch_host: "elasticsearch"
elasticsearch_port: 9200
elasticsearch_pass: "{{ lookup('env', 'FLASK_APP_ELASTICSEARCH_PASS') }}"

# Kibana
kibana_secret_key: "{{ lookup('env', 'FLASK_APP_KIBANA_SECRET_KEY') }}"

# RabbitMQ
rabbitmq_host: "rabbitmq"
rabbitmq_port: 5672
rabbitmq_user: "{{ lookup('env', 'FLASK_APP_RABBITMQ_USER') }}"
rabbitmq_pass: "{{ lookup('env', 'FLASK_APP_RABBITMQ_PASS') }}"

# Redis
redis_host: "redis"
redis_port: 6379

