on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Action Type'
        required: true
        options:
          - deploy-backend
          - deploy-services
          - deploy-logger
      branch:
        description: 'Source Branch'
        required: true
        options:
          - main

env:
  DEPLOY_TAG: ${{ inputs.tag }}
  HOST_SSH_PRIVATE_KEY: ${{ secrets.HOST_SSH_PRIVATE_KEY }}

jobs:
  deploy-main:
    if: ${{ inputs.branch }} == 'main'
    name: ${{ inputs.tag }}-main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

#      - name: Install ansible 
#        run: |
#          sudo apt install -y software-properties-common
#          sudo add-apt-repository --yes --update ppa:ansible/ansible
#          sudo apt install ansible

      - name: Add SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}

      - name: ssh test
        run: |
          ssh -v -o StrictHostKeyChecking=no ansible@217.160.151.99

#      - name: Run playbook
#        run: >
#          ansible-playbook 
#          -i inventory/flask-app 
#          -e env=main 
#          -l main 
#          -t $DEPLOY_TAG 
#          -v playbook.yml

