on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Action Type'
        required: true
        options:
          - deploy-backend
      branch:
        description: 'Source Branch'
        required: true
        options:
          - main

jobs:
  env:
    DEPLOY_TAG: ${{ inputs.tag }}
  deploy-main:
    if: ${{ inputs.branch }} == 'main'
    name: $DEPLOY_TAG-main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install ansible 
        run: |
          apt install -y software-properties-common
          add-apt-repository --yes --update ppa:ansible/ansible
          apt install ansible

      - name: Run playbook
        run: >
          ansible-playbook 
          -i inventory/flask-app 
          -e env=main 
          -l main 
          -t $DEPLOY_TAG 
          -v playbook.yml

